ningen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path

from ningen.interview import views as interview_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', interview_views.InterviewList.as_view(), name='interview-list'),
    path('about/', interview_views.about, name='about'),
    path('archives/', interview_views.archives, name='interview-archives'),
    path('archives/<int:year>/', interview_views.InterviewYearList.as_view(), name='interview-year-list'),
    path('tag/<slug:slug>', interview_views.InterviewTagList.as_view(), name='interview-tag-list'),
    path('interview/<slug:slug>/', interview_views.InterviewDetail.as_view(), name='interview-detail'),
]

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ningen/interview/models.py
from django.db import models
from django.utils import timezone


class Tag(models.Model):
    slug = models.SlugField(unique=True)

    class Meta:
        verbose_name = '标签'
        verbose_name_plural = '标签'

    def __str__(self):
        return self.slug


class Person(models.Model):
    MALE = 0
    FEMALE = 1

    GENDER_CHOICES = (
        (MALE, '男'),
        (FEMALE, '女')
    )

    slug = models.SlugField()
    name = models.CharField(max_length=32, verbose_name='称谓')
    gender = models.PositiveSmallIntegerField(
        choices=GENDER_CHOICES, verbose_name='性别')
    email = models.EmailField(unique=True, blank=True, verbose_name='邮件地址')

    class Meta:
        verbose_name = '人物'
        verbose_name_plural = '人物'

    def __str__(self):
        return self.name


class Item(models.Model):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=32, verbose_name='名称')
    vendor = models.CharField(max_length=32, blank=True, verbose_name='厂商')
    description = models.TextField(verbose_name='描述')
    link = models.URLField(verbose_name='链接')

    class Meta:
        verbose_name = '物品'
        verbose_name_plural = '物品'

    def __str__(self):
        return self.name

    def get_full_name(self):
        return "{0} {1}".format(self.vendor, self.name)


class Interview(models.Model):
    slug = models.SlugField(unique=True)
    person = models.ForeignKey(
        Person, on_delete=models.CASCADE, verbose_name='人物')
    title = models.CharField(max_length=32, blank=True, verbose_name='头衔')
    avatar = models.ImageField(upload_to='avatars', verbose_name='头像')
    company = models.CharField(
        max_length=32, blank=True, verbose_name='服务处所')
    education = models.CharField(
        max_length=32, blank=True, verbose_name='毕业院校')
    body = models.TextField(verbose_name='内容')
    tags = models.ManyToManyField(Tag, verbose_name='标签')
    create_on = models.DateTimeField(
        default=timezone.now, verbose_name='采访日期')

    class Meta:
        verbose_name = '采访稿'
        verbose_name_plural = '采访稿'

    def __str__(self):
        return self.slug

ningen/interview/views.py
from django.db.models import Count
from django.db.models.functions import TruncYear
from django.shortcuts import render
from django.views.generic import DetailView, ListView

from ningen.interview.models import Interview, Item, Tag


def about(request):
    """「关于」页面"""
    return render(request, 'about.html')


class InterviewDetail(DetailView):
    """采访详情页"""
    model = Interview


class InterviewList(ListView):
    """采访列表，默认作为「首页」"""
    model = Interview
    paginate_by = 5
    queryset = Interview.objects.all().order_by('-create_on')
    template_name = 'interview/interview_index.html'


def archives(request):
    """「采访」页面"""
    years = Interview.objects.annotate(year=TruncYear('create_on')) \
        .values('year').annotate(count=Count('id'))
    total_count = Interview.objects.count()
    tags = Tag.objects.all()
    item_count = Item.objects.count()
    return render(
        request, 'interview/interview_archives.html',
        {'years': years, 'total_count': total_count, 'tags': tags,
         'item_count': item_count})


class InterviewYearList(InterviewList):
    """年份采访列表"""
    template_name = 'interview/interview_year_list.html'

    def get_queryset(self):
        year = self.kwargs.get('year')
        return Interview.objects.filter(
            create_on__year=year).order_by('-create_on')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['year'] = self.kwargs.get('year')
        return context


class InterviewTagList(InterviewList):
    """分类采访列表"""
    template_name = 'interview/interview_tag_list.html'

    def get_queryset(self):
        tag_slug = self.kwargs.get('slug')
        return Interview.objects.filter(
            tags__slug=tag_slug).order_by('-create_on')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tag_slug'] = self.kwargs.get('slug')
        return context

templates/about.html
{% extends "base.html" %}

{% block title %}关于{% endblock title %}

{% block wrapper %}
<div class="wrapper">
  <div class="container clearfix">
    <div class="main half">
      <div class="content bordered ningen">
        <h3>Ningen 是什么？</h3>
        <p>Ningen 是一个无人问津的 Django Web 应用，是「人间」的采访项目。致力于：</p>
        <p>🙈 试验性地用全新方法阐述黑猩猩能利用树枝去捕食洞穴内的蚂蚁的原理。</p>
        <p>🤑 公开展示部分土豪的财产，为打倒土豪、劫富济贫收集证据。</p>
        <p><small class="muted">源码托管在 <a href="https://github.com/jinkanhq/ningen">Github</a> 上。</small></p>
      </div>
    </div>
    <div class="main half">
      <div class="content bordered ningen">
        <h3>常见问题</h3>
        <dl>
          <dt>🙄 如何选择采访对象？</dt>
          <dd>我们会根据鸽笼原理，通过基于土豆的人工智能「GLaDOS」分析存储在 /dev/random 的 42EB 数据。最终在未知的时间，由某位没有放鸽子的管理员进行伯努利实验，挑选「人间黑手」内定的人选。</dd>
          <dt>🍉 采访的问题会是哪些？</dt>
          <dd>
            <ol>
              <li>简要介绍一下自己，并且谈谈正在做什么？</li>
              <li>你使用的硬件有？</li>
              <li>你使用的软件有？</li>
              <li>你梦想中的设备是怎么样的？</li>
              <li class="muted"><del>「人间黑手」脱口而出的糟糕问题。</del></li>
            </ol>
          </dd>
        </dl>
      </div>
    </div>
  </div>
</div>
{% endblock wrapper %}

templates/base.html
<!doctype html>
<html class="no-js" lang="zh">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>人间 / {% block title %}{% endblock title %}</title>
  <meta name="generator" content="Ningen" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="「人间」无人问津的采访项目，关注采访者生活中的精巧工具，灵感源自 usesthis.com"/>
  {% block meta %}{% endblock meta %}
  <link rel="manifest" href="site.webmanifest">
  <link rel="apple-touch-icon" href="icon.png">
  <link rel="stylesheet" href="/static/style.css" type="text/css">
  <script>
    var _hmt = _hmt || [];
    (function () {
      var hm = document.createElement("script");
      hm.src = "https://hm.baidu.com/hm.js?2275dbd45900e3a78abdc3bf3659bb30";
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(hm, s);
    })();
  </script>
</head>

<body>
  <header class="topbar">
    <div class="container">
      <div class="content clearfix">
        <h1 class="logo">
          <a href="{% url 'interview-list' %}">Ningen</a>
        </h1>
        <nav>
          <ul>
            <li>
              <a href="{% url 'interview-list' %}">首页</a>
            </li>
            <li>
              <a href="{% url 'interview-archives' %}">采访</a>
            </li>
            <li>
              <a href="{% url 'about' %}">关于</a>
            </li>
            {% if user.is_superuser %}
            <li>
              <a href="/admin">管理后台</a>
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </div>
  </header>
  {% block wrapper %}
  <div class="wrapper">
    <div class="title container">
      <h2>{% block pagetitle %}欲盖弥彰{% endblock pagetitle %}</h2>
      <small class="muted">{% block subtitle %}人生天地之间，若白驹过隙，忽然而已。{% endblock subtitle %}</small>
    </div>
    <div class="container clearfix">
      <div class="main">
        <div class="content bordered clearfix">
          <img class="jinkan-logo" src="jinkan_logo_squa_blue_white.png" alt="">
          <p>2014 年 1 月 ～ 现在</p>
          <p>人间正道是沧桑。</p>
        </div>
      </div>
      <div class="main half">
        <div class="content bordered torri">
          <div class="content-header">
            <h3 class="bilingual">伪鸟居
              <small>TorriACG</small>
            </h3>
            <p>2009 年 12 月 ～ 2013 年 12 月</p>
          </div>
          <p>“伪鸟居”的“伪”字是纪念域名注册时某人手滑出的“鳥居（とりい）”的错误拼法。</p>
          <p>“伪鸟居”曾经是五人撰写内容的 Blog。
            <br> 2010 年 11 月后，启用域名 torriacg.org。
            <br> 2012 年 6 月起，关闭 Blog，开始酝酿新计划。</p>
          <h4>鸣谢</h4>
          <ul>
            <li>BK：打着中二病幌子的新番点评小剧场</li>
            <li>Nt.：漫画、游戏评论和技术笔记，目前其余状况不明。</li>
            <li>Virgil：歌词苦力和音乐赏析，目前疑似专心
              <a href="http://sakebukemono.vip.5sing.com/default.aspx">翻唱事业</a>。</li>
          </ul>
        </div>
      </div>
      <div class="main half">
        <div class="content bordered ancient">
          <div class="content-header">
            <h3 class="bilingual">先代
              <small>The Ancient</small>
            </h3>
            <p>2009 年 6 月 ～ 2009 年 11 月</p>
          </div>
          <p>
            <del>该时期的追求是国内领先，国际闻名。</del>
            <br>
            <small class="muted">（不明真相群众请勿拍砖）</small>
          </p>
          <h4>鸣谢</h4>
          <ul>
            <li>某D：状况不明</li>
            <li>某L：状况不明</li>
            <li>某S：状况不明</li>
            <li>某Y：状况不明</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div id="projects" class="wrapper">
    <div class="title container">
      <h2>好事多磨</h2>
      <small class="muted">等青春轻飘的烟雾把少年的欢乐袅袅曳去，之后，我们就能取得一切值得吸取的东西。</small>
    </div>
    <div class="container clearfix">
      <div class="main third">
        <div class="content colored docs">
          <h3 class="bilingual">文档翻译计划
            <small>Docs Project</small>
          </h3>
        </div>
        <div class="content">
          <p>上线于
            <a href="http://docs.jinkan.org">docs.jinkan.org</a>。</p>
          <p>利用 Github WebHook 实现的自动化文档构建系统，目前仅支持 Sphinx。</p>
        </div>
      </div>
      <div class="main third">
        <div class="content colored">
          <h3>不明真相的 SETUP</h3>
        </div>
        <div class="content">
          <p>上线于
            <a href="http://setup.jinkan.org">setup.jinkan.org</a>。</p>
          <p>消费电子沉迷患者访谈与设备展示。
            <small class="muted">
              <del>为打倒土豪分财产提供有效证据支持。</del>
            </small>
          </p>
          <p>源码托管在
            <a href="https://github.com/jinkanhq/setup">Github</a> 上。</p>
        </div>
      </div>
      <div class="main third">
        <div class="content colored soundside">
          <h3 class="bilingual">声旁
            <small>SoundSide</small>
          </h3>
        </div>
        <div class="content">
          <p>孵化中…</p>
          <p>不只是一个数字乐谱分享项目。</p>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper">
    <div class="title container">
      <h2>明修栈道</h2>
      <small class="muted">居善地，心善渊，与善仁，言善信，正善治，事善能，动善时。夫唯不争，故无尤。</small>
    </div>
    <div class="main container">
      <div class="content">
        <ul>
          <li>社区
            <ul>
              <li>
                <a href="https://github.com/jinkanhq">Github/JinkanHQ</a>
              </li>
              <li>
                <a href="http://steamcommunity.com/groups/jinkan">Steam/人间社</a>
              </li>
              <li>
                <a href="https://plus.google.com/communities/103127398566493450878">Google+/人间社</a>
              </li>
            </ul>
          </li>
          <li>即时通讯
            <ul>
              <li>QQ群：35973757</li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
  <div class="wrapper">
    <div class="title container">
      <h2>一丘之貉</h2>
      <small class="muted">我们都是來自五湖四海，为了一个共同的革命目标，走到一起來了。</small>
    </div>
    <div class="container clearfix">
      <div class="main third">
        <div class="content bordered hd">
          <div class="content-header">
            <img class="avatar" src="hexiezhifeng.jpg" alt="">
            <h3>和谐之风</h3>
            <span>hd@jinkan.org</span>
          </div>
          <ul>
            <li>幕后黑手</li>
            <li>肉翻实践者</li>
            <li>富可敌国</li>
          </ul>
        </div>
      </div>
      <div class="main third">
        <div class="content bordered midare">
          <div class="content-header">
            <img class="avatar" src="midare.jpg" alt="">
            <h3>乱序</h3>
            <span>midare@jinkan.org</span>
          </div>
          <ul>
            <li>前端与美工</li>
            <li>理想主义</li>
            <li>现实生活很充实</li>
          </ul>
        </div>
      </div>
      <div class="main third">
        <div class="content bordered yinian">
          <div class="content-header">
            <img class="avatar" src="yinian1992.jpg" alt="">
            <h3>亦念</h3>
            <span>yinian@jinkan.org</span>
          </div>
          <ul>
            <li>普通的魔法使</li>
            <li>拖延症患者</li>
            <li>卖得一手好萌</li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="wrapper">
    <div class="title container">
      <h2>人杰地灵</h2>
      <small class="muted">海纳百川，有容乃大。壁立千仞，无欲则刚。</small>
    </div>
    <div class="main container">
      <div class="content">
        <ul>
          <li>老邻居
            <ul>
              <li>
                <a href="http://venusxx.gzocean.net">Do You Love Me ?</a>
              </li>
              <li>
                <a href="http://imoe.us/">Hello Letter</a>
              </li>
              <li>
                <a href="http://crazism.net/">Crazism</a>
              </li>
              <li>
                <a href="http://mjmkacg.com/">MJMK's ACG</a>
              </li>
              <li>
                <a title="Anime Share &amp; Celebrate Thinking" href="http://moe.akibarika.org">Orclandでの思い出の欠片</a>
              </li>
              <li>
                <a href="http://www.lolibeta.com/">LoliBeta</a>
              </li>
              <li>
                <a href="http://acgtea.com">动漫茶馆</a>
              </li>
              <li>
                <a href="http://mouto.org">卜卜口の猫窝</a>
              </li>
              <li>
                <a href="http://www.jiongtz.com/">囧TZ</a>
              </li>
              <li>
                <a href="http://bitinn.net/">比特客栈的文艺复兴</a>
              </li>
              <li>
                <a href="http://www.moejoy.com/">萌之轨迹</a>
              </li>
              <li>
                <a href="http://xloli.net/">TesliaX</a>
              </li>
              <li>
                <a href="http://ololi.com/">蒼炎異域</a>
              </li>
            </ul>
          </li>
          <li>墓地
            <ul>
              <li>Is Dear - www.dearsama.com</li>
              <li>時の風 - thegreatmusic.info</li>
              <li>WINDMOE - windmoe.com</li>
              <li>吐槽志 - xxloli.com</li>
              <li>Lo极乐园 - blog.lolily.com</li>
              <li>Minus-Se7en - fujis.org</li>
              <li>大宅萌 - www.wocomic.cn</li>
              <li>工口堂 - www.moeu.net</li>
              <li>肘子的博客 - zhouzi.info</li>
              <li>萌の空 - moesora.com</li>
              <li>FourLeafSheets - fourleafsheets.com</li>
              <li>冥月汉化组 - bbs.dmacgn.com</li>
            </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
  {% endblock wrapper %}
  <footer class="footer container">
    Powered by Ningen, inspired by <a href="https://usesthis.com">usesthis.com</a>.
    <br> &copy; Jinkan 2009-2018 All rights reserved. 京ICP备10003487号-2
  </footer>
</body>

</html>

templates/interview/interview_archives.html
{% extends "base.html" %}

{% block title %}采访{% endblock title %}

{% block wrapper %}
<div class="wrapper">
  <div class="container clearfix">
      <div class="main content archives">
        <h2>采访</h2>
        <p>截至目前共有 {{ total_count }} 篇采访，涉及物件 {{ item_count }} 种。</p>
        <h3>按年份：</h3>
        <ul>
          {% for year_group in years %}
          <li><a href="{% url 'interview-year-list' year_group.year|date:'Y' %}">{{ year_group.year|date:'Y' }}</a> ({{ year_group.count }})</li>
          {% endfor %}
        </ul>
        <h3>按分类：</h3>
        {% for tag in tags %}
        <a class="tag" href="{% url 'interview-tag-list' tag.slug %}">{{ tag.slug }}</a>
        {% empty %}
        <span class="muted">暂无分类。</span>
        {% endfor %}
      </div>
    </div>
  </div>
</div>
{% endblock wrapper %}

templates/interview/interview_detail.html
{% extends "base.html" %}
{% load static %}
{% load markdown %}

{% block meta %}
<meta property="og:type" content="article" />
<meta itemprop="name" property="og:title" content="{{ interview.person.name }}">
<meta itemprop="description" property="og:description" content="{{ interview.title }} ({{ interview.company }})，采访于 {{ interview.create_on }}。">
<meta itemprop="image" property="og:image" content="{{ request.scheme }}://{{ request.get_host }}{{ interview.avatar.url }}">
<meta property="og:url" content="{{ request.scheme }}://{{ request.get_host }}{% url 'interview-detail' interview.slug %}">
{% endblock meta %}

{% block title %}{{ interview.person.name }}{% endblock title %}

{% block wrapper %}
<div class="wrapper">
  <div class="title container interview">
    <div class="content bordered ningen">
      <div class="avatar" style="background-image:url({{ interview.avatar.url }})"></div>
      <h2 class="person name">{{ interview.person.name }}</h2>
      <span class="person title muted">{{ interview.title }} ({{ interview.company }})</span>
      <div class="meta muted">
        采访于 {{ interview.create_on }}，分类为
        {% for tag in interview.tags.all %}
        <a class="tag" href="{% url 'interview-tag-list' tag.slug %}">{{ tag.slug }}</a>
        {% empty %}
        <a class="tag" href="javascript:;">Unique</a>
        {% endfor %}
      </div>
    </div>
  </div>
  <div class="main container interview">
    <div class="content bordered ningen">
      <div class="markdown">
        {{ interview.body | markdown }}
      </div>
    </div>
  </div>
</div>
{% endblock wrapper %}

templates/interview/interview_index.html
{% extends "base.html" %}

{% block title %}首页{% endblock title %}

{% block wrapper %}
<div class="wrapper">
  {% include "interview/interview_list.html" with object_list=object_list page_obj=page_obj %}
</div>
{% endblock wrapper %}

templates/interview/interview_list.html
{% for interview in object_list %}
<div class="title container interview">
  <div class="content bordered ningen">
    <div class="avatar" style="background-image:url({{ interview.avatar.url }})"></div>
    <h2 class="person name">
        <a href="{% url 'interview-detail' interview.slug %}">{{ interview.person.name }}</a>
    </h2>
    <span class="person title muted">{{ interview.title }} ({{ interview.company }})</span>
    <div class="meta muted">
      采访于 {{ interview.create_on }}，分类为
      {% for tag in interview.tags.all %}
      <a class="tag" href="{% url 'interview-tag-list' tag.slug %}">{{ tag.slug }}</a>
      {% endfor %}
    </div>
  </div>
</div>
{% empty %}
{% endfor %}
<div class="pagination container">
  <div class="content clearfix">
    <div class="previous">
      {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">更新的采访&rarr;</a>
      {% endif %}
    </div>
    <div class="next">
      {% if page_obj.has_next %}
      <a href="?page={{ page_obj.next_page_number }}">&larr;更早的采访</a>
      {% endif %}
    </div>
  </div>
</div>
</div>

templates/interview/interview_tag_list.html
{% extends "base.html" %}

{% block title %}{{ tag_slug }} {% endblock title %}

{% block wrapper %}
<div class="wrapper">
  <div class="title container list">
    <h2>{{ tag_slug }}</h2>
  </div>
  {% include "interview/interview_list.html" with object_list=object_list page_obj=page_obj %}
</div>
{% endblock wrapper %}

templates/interview/interview_year_list.html
{% extends "base.html" %}

{% block title %}{{ year }} 年{% endblock title %}

{% block wrapper %}
<div class="wrapper">
  <div class="title container list">
    <h2> {{ year }} 年</h2>
  </div>
  {% include "interview/interview_list.html" with object_list=object_list page_obj=page_obj %}
</div>
{% endblock wrapper %}